defaults:
  - hydra/launcher: slurm
  - training: bbcpose

slurm:
  gres: gpu:1
  job_name:
    - example
  partition: gpu
  cpus_per_task: 4
  ntasks_per_node: 1
  mem: 22G
  nodes: 1
  qos: normal

singularity:
  bin_path: '/h/dturpin/pkgs/bin/singularity'
  sbox_path: '/h/dturpin/img/UnsupervisedLandmarkLearning_sbox'
  
exec_path: '/h/dturpin/repos/UnsupervisedLandmarkLearning/train.py'
